### PR TITLE
PDF versions of images

### PR DESCRIPTION
**Pull request by peterkelly**
The .png files are hard to read, especially on a retina display. I've created .pdf equivalents of each.

### CODE REVIEW

**Comment by peterkelly** [comment]
So I just realised that the build process creates PDFs. Still, if the .png files are going to be in the repository (where I saw them initially), might as well have PDF versions too. https://github.com/gulpjs/gulp/blob/master/docs/README.md#articles links to the github repo, so instead of seeing .png files or having to download & build themselves, with this commit people can look at the pdfs straight away.

**Comment by cognitom** [comment]
@peterkelly doesn't make sense for me...
We have PDFs already?
https://github.com/osscafe/gulp-cheatsheet/tree/master/dist

**Comment by peterkelly** [comment]
And I just realised they're directly linked from the readme (facepalm)

This pull request can be closed now

**Comment by cognitom** [comment]
No prob. Thanks for having interest on the project 😸

**Pull request closed without merging**
